### ISSUE TITLE
use_texture_alpha = "clip"

### ISSUE THREAD

**Issue by Bastrabun** [mt-mods/abritorch#5]
I have a couple of those:

2023-06-04 19:51:04: WARNING[Main]: Texture "abritorch_torch_on_floor_animated_black.png" of abritorch:torch_black has transparency, assuming use_texture_alpha = "clip".

Can you please add `use_texture_alpha = "clip"` them after the  3 places:

https://github.com/mt-mods/abritorch/blob/master/torches.lua#L16
https://github.com/mt-mods/abritorch/blob/master/torches.lua#L47
https://github.com/mt-mods/abritorch/blob/master/torches.lua#L75

For my reference 4213 .9

**Comment by wsor4035** [comment]
ignored your last two as https://github.com/mt-mods/abritorch/blob/a2225116045df67bf921c076d68e95fcc32977e6/torches.lua#L54 and https://github.com/mt-mods/abritorch/blob/a2225116045df67bf921c076d68e95fcc32977e6/torches.lua#L81 exist
